# Generated by Django 4.0.4 on 2022-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tpaisserviciodefix_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpais',
            name='coin',
            field=models.TextField(blank=True, help_text='Mondeda del Pais', max_length=120, null=True),
        ),
    ]
