# Generated by Django 4.0.4 on 2022-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_tpais_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaisdocumento',
            name='detalle',
            field=models.TextField(blank=True, help_text='Caracteristicas del documento', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='tpaisdocumento',
            name='juridico',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Juridico')], default='N', help_text='Natural o Juridico', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tpaisdocumento',
            name='opcional',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', help_text='Opcional Si o No', max_length=1, null=True),
        ),
    ]
