# Generated by Django 4.0.4 on 2022-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tpaisdocumento_detalle_tpaisdocumento_juridico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpais',
            name='kyccompra',
            field=models.BooleanField(default=True, help_text='Esta activo?'),
        ),
        migrations.AddField(
            model_name='tpais',
            name='kycventa',
            field=models.BooleanField(default=True, help_text='Esta activo?'),
        ),
    ]
