# Generated by Django 4.0.4 on 2022-10-20 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_tpais_kyccompra_tpais_kycventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='tkycCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('R', 'Revision'), ('A', 'Aprobada'), ('C', 'Cancelada')], default='R', max_length=1)),
                ('observacion', models.TextField(blank=True, help_text='usuario con registros de kyc', max_length=240, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha de inicio de la transaccion', null=True)),
                ('fecha_final', models.DateTimeField(blank=True, help_text='Fecha de fin de la transaccion', null=True)),
                ('juridico', models.CharField(help_text='Natural o Juridico', max_length=1, null=True)),
                ('pais', models.ForeignKey(blank=True, help_text='Pais asociado', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
                ('usuario', models.ForeignKey(help_text='usuario asociado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tkycDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('R', 'Revision'), ('A', 'Aprobada'), ('C', 'Cancelada')], default='R', max_length=1)),
                ('texto', models.TextField(help_text='texto...', max_length=150, null=True)),
                ('imagen', models.ImageField(default='default.jpg', help_text='Imagen KYC', null=True, upload_to='archivoskyc')),
                ('observacion', models.TextField(blank=True, help_text='usuario con registros de kyc', max_length=240, null=True)),
                ('kyccabecera', models.ForeignKey(blank=True, help_text='Id de KYC asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tkyccabecera')),
                ('paisdocumento', models.ForeignKey(blank=True, help_text='Documento KFC pos Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tpaisdocumento')),
            ],
        ),
    ]
