# Generated by Django 4.0.4 on 2022-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_tkyccabecera_tkycdetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkycdetalle',
            name='documento',
            field=models.TextField(blank=True, help_text='documnto', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tkycdetalle',
            name='texto',
            field=models.TextField(blank=True, help_text='texto...', max_length=150, null=True),
        ),
    ]
