# Generated by Django 4.0.4 on 2022-10-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0009_tkycdetalle_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkyccabecera',
            name='usuario',
            field=models.ForeignKey(help_text='usuario asociados', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
