# Generated by Django 4.0.4 on 2022-10-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_tkyccabecera_banco_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkycdetalle',
            name='imagen',
            field=models.ImageField(help_text='Imagen KYC', null=True, upload_to='archivoskyc'),
        ),
        migrations.AlterField(
            model_name='tkycdetalle',
            name='tipo',
            field=models.CharField(help_text='Tipo de documento', max_length=1, null=True),
        ),
    ]
