# Generated by Django 4.0.4 on 2022-10-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_ttipopago_tpaisbanco_tkyccuentas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tkycCuentas',
            new_name='tkycCuenta',
        ),
    ]
