# Generated by Django 4.0.4 on 2022-11-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_tkyccuentas_tkyccuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='tkycCuentaDefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.TextField(blank=True, help_text='Nombre del Titular', max_length=150, null=True)),
                ('cedula', models.TextField(blank=True, help_text='Numero de Identificacion', max_length=20, null=True)),
                ('telefono', models.TextField(blank=True, help_text='Numero de telefono', max_length=50, null=True)),
                ('numerocuenta', models.TextField(blank=True, help_text='numero de cuenta del titular', max_length=20, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('banco', models.ForeignKey(blank=True, help_text='Id de Banco Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tpaisbanco')),
                ('pais', models.ForeignKey(help_text='Pais asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
                ('tipopago', models.ForeignKey(blank=True, help_text='Id de tipo de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ttipopago')),
            ],
        ),
    ]
