# Generated by Django 4.0.4 on 2022-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_tkyccuentadefix_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpaisbanco',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo del Banco 4 digitos', max_length=20, null=True),
        ),
    ]
