# Generated by Django 4.0.4 on 2022-11-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_tpaisbanco_logo_tpaisbanco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpais',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='tasa de conversion', max_digits=10),
        ),
    ]
