# Generated by Django 4.0.4 on 2022-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_tpais_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpais',
            name='tasa',
            field=models.TextField(blank=True, help_text='tasa', max_length=120, null=True),
        ),
    ]
