# Generated by Django 4.0.4 on 2022-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_tkyccuentadefix_tipocuenta_fiattransaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='estatus',
            field=models.CharField(choices=[('C', 'Creado'), ('A', 'Asignado'), ('P', 'Procesado'), ('C', 'Completado'), ('X', 'Anulado')], default='C', max_length=1),
        ),
    ]
