# Generated by Django 4.0.4 on 2022-11-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_fiattransaccion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='accion',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venta')], default='C', max_length=1),
        ),
    ]
