# Generated by Django 4.0.4 on 2022-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_tkyccuenta_tipocuenta_alter_fiattransaccion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattransaccion',
            name='cantidad',
            field=models.TextField(blank=True, help_text='cantidad de la criptomoneda', max_length=20, null=True),
        ),
    ]
