# Generated by Django 4.0.4 on 2022-11-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_fiattransaccion_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='estatus',
            field=models.CharField(choices=[('1', 'Creado'), ('2', 'Asignado'), ('3', 'Procesado'), ('4', 'Completado'), ('5', 'Anulado')], default='1', max_length=1),
        ),
    ]
