# Generated by Django 4.0.4 on 2022-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_fiattransaccion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_anulado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro aunulado'),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro completado'),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro procesado'),
        ),
    ]
