# Generated by Django 4.0.4 on 2022-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_fiattransaccion_fecha_anulado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_anulado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro aunulado', null=True),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro', null=True),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro completado', null=True),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, help_text='fecha de registro procesado', null=True),
        ),
    ]
