# Generated by Django 4.0.4 on 2022-11-09 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_fiattransaccion_fecha_anulado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='cantidad de la criptomoneda', max_digits=14),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tasa de cambio', max_digits=14),
        ),
    ]
