# Generated by Django 4.0.4 on 2022-11-09 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_fiattransaccion_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattransaccion',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='comision', max_digits=14),
        ),
        migrations.AlterField(
            model_name='fiattransaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto', max_digits=14),
        ),
    ]
