# Generated by Django 4.0.4 on 2022-11-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_fiattransaccion_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattransaccion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='adjunto soporte de la venta o compra', null=True, upload_to='fiat'),
        ),
    ]
