# Generated by Django 4.0.4 on 2022-11-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_fiattransaccion_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiattransaccion',
            old_name='imagen',
            new_name='adjunto',
        ),
    ]
