# Generated by Django 4.0.4 on 2022-11-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_rename_imagen_fiattransaccion_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiattransaccion',
            name='adjunto',
        ),
    ]
