# Generated by Django 4.0.4 on 2022-11-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_fiattransaccion_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattransaccion',
            name='adjuntofiat',
            field=models.ImageField(blank=True, help_text='adjunto soporte de la venta o compra', null=True, upload_to='fiat'),
        ),
    ]
