# Generated by Django 4.0.4 on 2022-11-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_fiattransaccion_adjuntofiat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiattransaccion',
            name='adjuntofiat',
        ),
    ]
