# Generated by Django 4.0.4 on 2022-11-17 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_fiattransaccion_adjuntofiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpais',
            name='montocompra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto minimo para compras FIAT', max_digits=14),
        ),
        migrations.AddField(
            model_name='tpais',
            name='montoventa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto minimo para ventas FIAT', max_digits=14),
        ),
    ]
