# Generated by Django 4.0.4 on 2022-11-21 12:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_tpais_montocompra_tpais_montoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('S', 'Super'), ('A', 'Admin'), ('U', 'Usuario'), ('B', 'Banco'), ('D', 'Defix')], default='U', help_text='Tipo de usuario', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='tPaisBancoRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa', max_digits=14)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto a validar para montos altos', max_digits=14)),
                ('tasaaltosmontoso', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa a aplicar con altos montos', max_digits=14)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('banco', models.ForeignKey(help_text='Banco asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpaisbanco')),
                ('pais', models.ForeignKey(help_text='Pais asociado', on_delete=django.db.models.deletion.CASCADE, to='backend.tpais')),
            ],
        ),
    ]
