# Generated by Django 4.0.4 on 2022-11-21 13:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_alter_perfil_tipo_tpaisbancorango'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaisbanco',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto a validar para montos altos', max_digits=14),
        ),
        migrations.AddField(
            model_name='tpaisbanco',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa', max_digits=14),
        ),
        migrations.AddField(
            model_name='tpaisbanco',
            name='tasaaltomonto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='tasa a aplicar con altos montos', max_digits=14),
        ),
    ]
