# Generated by Django 4.0.4 on 2022-11-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_tpaisbanco_monto_tpaisbanco_tasa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tPaisBancoRango',
        ),
    ]
