# Generated by Django 4.0.4 on 2022-12-19 17:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_tpaisbanco_montominv_tpaisbanco_montov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaisbanco',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='comision compra', max_digits=14),
        ),
        migrations.AddField(
            model_name='tpaisbanco',
            name='comisionv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='comision compra', max_digits=14),
        ),
    ]
