# Generated by Django 4.0.4 on 2022-12-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_tpaisbanco_comision_tpaisbanco_comisionv'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattransaccion',
            name='wallet',
            field=models.TextField(blank=True, help_text='wallet', max_length=240, null=True),
        ),
    ]
