# Generated by Django 4.0.4 on 2023-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_cryptocurrency_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='coin',
            field=models.CharField(max_length=32),
        ),
    ]
