# Generated by Django 4.0.4 on 2023-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_rename_nombre_token_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
