# Generated by Django 4.0.4 on 2023-02-16 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_tuserfiat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuserfiat',
            old_name='codigo',
            new_name='token',
        ),
        migrations.AddField(
            model_name='tuserfiat',
            name='creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='fecha de creacion de token'),
        ),
        migrations.AlterField(
            model_name='tuserfiat',
            name='activo',
            field=models.BooleanField(default=True, help_text='esta el token activo?'),
        ),
    ]
