# Generated by Django 4.0.4 on 2023-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_rename_token_tuserfiat_tokenemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='icon',
            field=models.ImageField(help_text='icon Crypto', null=True, upload_to='media/icons'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='swap',
            field=models.BooleanField(default=False, help_text='swap habilitado?'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='time_transaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='icon',
            field=models.ImageField(help_text='icon Crypto', null=True, upload_to='media/icons'),
        ),
    ]
