# Generated by Django 4.0.4 on 2023-03-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_cryptocurrency_icon_cryptocurrency_swap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='time_transaction',
            field=models.IntegerField(blank=True, help_text='time in seconds', null=True),
        ),
    ]
