# Generated by Django 4.0.4 on 2023-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_remove_tdatacrypto_amount_remove_tdatacrypto_colorg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='limit',
            field=models.BooleanField(default=False, help_text='limit habilitado?'),
        ),
    ]
