# Generated by Django 4.0.4 on 2023-05-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_rename_limit_cryptocurrency_limitorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='limitOrder',
            new_name='limit_order',
        ),
    ]
