# Generated by Django 4.0.4 on 2023-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_rename_limitorder_cryptocurrency_limit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='bridge',
            field=models.BooleanField(default=False, help_text='bridge habilitado?'),
        ),
    ]
