# Generated by Django 4.0.4 on 2023-06-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_cryptocurrency_bridge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tdatacrypto',
            old_name='token',
            new_name='wallet_defix',
        ),
    ]
